version: 2
jobs:
  build:
    docker:
      - image: tgrant/sunburst-react-boilerplate-circleci:0.0.1
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: make node_modules

      - save_cache:
          paths:
            - node_modules
          key: deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint JS
          command: make eslint
          when: always

      - run:
          name: Lint CSS
          command: make stylelint
          when: always

      - run:
          name: Run Tests
          command: make test
          when: always

      - run:
          name: Build App
          command: PROD=1 make build

      - run:
          name: Run E2Es locally
          command: |
            PROD=1 make start &
            sleep 5
            E2E_TARGET=local make test-e2e

      - store_artifacts:
          path: artifacts

      - store_test_results:
          path: artifacts/test_results

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ./
          # Must be relative path from root
          paths:
            - artifacts/
            - node_modules/

  deploy:
    docker:
      - image: tgrant/sunburst-react-boilerplate-circleci:0.0.1
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy Staging
          command: make deploy-staging

      - run:
          name: Run E2Es on staging
          command: |
            PROD=1 make start &
            sleep 5
            E2E_TARGET=staging make test-e2e

      - run:
          name: Deploy Production
          command: make deploy-production

      - run:
          name: Run E2Es on production
          command: |
            PROD=1 make start &
            sleep 5
            E2E_TARGET=production make test-e2e

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

experimental:
  notify:
    branches:
      only:
        - master
