version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6.0
    working_directory: ~
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: make node_modules

      - save_cache:
          paths:
            - node_modules
          key: deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint JS
          command: make eslint
          when: always

      - run:
          name: Lint CSS
          command: make stylelint
          when: always

      - run:
          name: Run Tests
          command: make test
          when: always

      - run:
          name: Build App
          command: PROD=1 make build

      - store_artifacts:
          path: artifacts

      - store_test_results:
          path: artifacts/test_results

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts/
            - node_modules/

#  deploy:
#    docker:
#      - image: circleci/node:8.6.0
#    working_directory: ~
#    steps:
#      - checkout
#
#      - attach_workspace:
#          at: ~
#
#      - run:
#          name: Install Deployment Dependencies
#          command: make install-deployment-deps
#
#      - run:
#          name: Deploy Staging
#          command: make deploy-staging
#
#      - run:
#          name: Deploy Production
#          command: make deploy-production
#
#workflows:
#  version: 2
#  build_and_deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
